### PR TITLE
simplify search state management using swr, add user-surfaced validation and error handling

### PR DESCRIPTION
**Pull request by lostfictions**
you can go through the commits step-by-step, but here's a quick summary:

- some bookkeeping -- added a `.node-version` file, `packageManager` field to `package.json`, devcontainer definition, `.prettierrc` (i have [`prettier.requireConfig`](https://github.com/prettier/prettier-vscode#prettierrequireconfig-default-false) enabled to avoid churning random other files i open on my computer), eslint + config, and the missing lockfile
- removed the old Next files for now -- they're still in git if we need them 🙂 
- refactored stateful components to have a common React parent
- simpified request state management with `swr` -- this helps with loading states, error states, someone slamming the button a million times, etc
- surfaced validation errors in a nicer way with `react-hook-form` -- this has nice faculties for surfacing validation errors to the user, and some nice ux stuff (for example, validation behaviour when a form field hasn't yet been submitted vs when it's "dirty").
- removed nanostores since it's no longer necessary

EDIT: also removed the cors headers and netlify configuration from the astro config -- as far as i can tell they're not necessary right now. @oxgr, i think maybe the problem you were running into is that a request to the opennorth api that has incorrect parameters comes back with incorrect cors headers -- unfortunately, that's a problem on their end, and i don't think adding cors headers to our own site is going to change that. (you can check for yourself -- most requests will work, but if you put `z0z0z0` in the search box it'll flip. because of the missing cors headers, this category of error is totally opaque to our code; that is, without the proper headers on their end it's obscuring any more helpful error message the API might be trying to send. they might be trying to give a 5xx status or something, but the browser only throws at the request site as a `TypeError`.)

i'll try to make smaller, more digestible PRs next time, i was working a bit hastily tonight!

### CODE REVIEW

**Comment by oxgr** [comment]
neat! interesting note on the cors: that def has to be it cos `curl`ing an endpoint with a moot postal code returns an error html page, prob with the status code to go with it.

netlify adapter was just for using `netlify-cli`. dont think its necessary if we manually upload. running a pre-made gh workflow would be prety nice tho...

great work on input error handling. im def not familiar w the right tools for it so this is invaluable.

**Review by oxgr — APPROVED** [review]
sweet! def feel like these first few PRs will be big while we iron out structure, but thats okay!

**Comment by lostfictions** [comment]
> netlify adapter was just for using `netlify-cli`. dont think its necessary if we manually upload. running a pre-made gh workflow would be prety nice tho...

@oxgr yeah imo if we're using netlify it only really reduces friction if we're using the github integration with branch previews etc. -- otherwise i think it's much simpler to use github pages.

this is doubly true if nobody has a paid netlify team account to run it off of... unfortunately netlify doesn't have shared access control outside of team plans, which means only one person will have access to netlify to debug build issues etc. 

for myself, i don't really use netlify for organizational websites or anything that needs to be shared because of this... it's just not worth it when gh-pages is just as fast and easy and can reuse repo access.

**Comment by oxgr** [comment]
+! on gh-pages. rn, alex shared login credentials w me, but that's not sustainable for more collaborators.

could run a basic workflow to auto-build.

only possible issue is domain is tied to @liminalfun unless we get one. mb non-issue?

**Pull request merged**
